import React from 'react'

import { makeStyles } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';
import Dialog from '@material-ui/core/Dialog';
import AppBar from '@material-ui/core/AppBar';
import Toolbar from '@material-ui/core/Toolbar';
import Typography from '@material-ui/core/Typography';
import Slide from '@material-ui/core/Slide';
import Container from '@material-ui/core/Container';

const useStyles = makeStyles(theme => ({
  appBar: {
    position: 'relative',
  },
  title: {
    marginLeft: theme.spacing(2),
    flex: 1,
  },
  button: {
    margin: theme.spacing(1),
  },

}));

const Transition = React.forwardRef(function Transition(props, ref) {
  return <Slide direction="up" ref={ref} {...props} />;
});


const PrivacyPolicy = () => {

  const classes = useStyles();
  const [open, setOpen] = React.useState(false);

  function handleClickOpen() {
    setOpen(true);
  }

  function handleClose() {
    setOpen(false);
  }

  let legalIpsum = [];
  const legalIpsumText = [
    'Subject to the intellectual property rights of any payment or license. In the absence of any Contributor under this Agreement. Licensed Product, and you want it, that you distribute of the material terms or conditions of Clause 6, above, are met for every component of the possibility of such entity. Contribution." "Contributor" shall mean the union of the General Public License does not infringe the patent or other fee is hereby granted, provided that each external component clearly identifies itself as the Derived Program under their own license agreement, such license applies only to those patent claims licensable by a Contributor, and only if you distribute copies of Original Code the copyright holder saying it may be required by applicable law) under this Agreement, including all modules it contains, plus any associated interface definition files, scripts used to endorse or promote products or services of Licensee, or any other intellectual property rights (other than as may be filtered to exclude very small or irrelevant contributions.) This applies to any "LaTeX-Format", and both "Copyright Holder" and "Current Maintainer" A person or entity that distributes the Program, modifications to the Work, provide any other combinations which include the Program (independent of having been made by previous Contributors, are available for at least twelve (12) months after a new version of the General Public License instead.) You can apply it to code to which you hold the copyright holder who places the Program by such Contributor itself or anyone acting on such Contributor"s behalf.',
    'Contributions do not Distribute the result without restriction, provided the appropriate decompression or de-archiving software is covered only if you distribute copies of NetHack, provided that you are re-using, b) a copy of this Agreement, including but not limited to, the implied warranties or conditions of this License, each Contributor hereby grants Recipient a non-exclusive, royalty-free, perpetual, irrevocable license, under Your choice of the United States of America, any litigation relating to any Contributor. You must retain, in the Program (including Contributions) may always continue to use any Apple Marks in or among countries not thus excluded. In such case, this License with information on how to get the Source Code. You may act only on your own behalf, and not on behalf of all Your Modifications, and the following places: within a display generated by the Current Maintainer upon request provided they then update their communication data within one month. If the Recipient retains any such Licensed Product and has been certified as open source.',
    'It has also been designated as GPL compatible by the Package. Licensed Product. If you become aware that the distribution of a Digital Font Program newly created by various software programs from you with this Package. To protect your rights under this Agreement, and without fee is required.',
    'Both Source Code form under the terms and conditions of this definition, "control" means (a) the power, direct or indirect, to cause the direction or management of such work; and (b) in the course of creating the Derived Program to a third party. By copying, installing or otherwise designated in writing will The Copyright Holder, and derivatives of that Derived Work may be called "PHP", nor may "openSEAL" appear in the case (e.g., if a court of competent jurisdiction finds any provision of this license agreement ("Agreement"). Any use, modification, and distribution of Your choice, which may be filtered to exclude very small or irrelevant contributions.) This applies to any actual or alleged intellectual property rights needed, if any.',
    'It is provided "as is" without express or implied warranty. Redistribution and use in the documentation and/or other materials provided with the Commercial Contributor then makes performance claims, or offers warranties related to those contained in this License will not be used in this License. Code" are defined in this section to claim rights or to endorse or promote products derived from it, be made available by Apple under this License with information on how and where to get the source code must retain and reproduce in all copies and that you create or to which Licensor or its representatives, including but not limited to, the substance and/or structure of said Licensed Product.',
    'Hereinafter in this Agreement. Except as expressly stated in writing, shall any Contributor to pay any damages as a result of a change completed under the terms of this Agreement, each Contributor hereby grants Recipient a non-exclusive, worldwide, royalty-free patent license shall not apply to any such Licensed Program from such Contributor, if any, must include a copy of the work cannot be construed against the Indemnified Contributor to the version of this BeOpen Python License is a "commercial item," as that Compiled Work that the Package (either the Standard or Modified Versions without the Source Code of the changes and/or additions to the licenses granted by such Participant under Sections 1 and 2 automatically terminate upon a material breach of its terms and conditions in this distribution used to render or display fonts. Program" shall mean a computer system. This processing may include your modifications in the executable runs, unless that component is made available from "http://www.php.net/". THIS SOFTWARE IS PROVIDED BY THE PHP DEVELOPMENT TEAM "AS IS" AND ANY EXPRESSED OR IMPLIED INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.',
    'IN NO EVENT SHALL ZOPE CORPORATION "AS IS" AND ANY EXPRESS OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE OR THAT THE USE OR INABILITY TO USE THE COVERED CODE PROVE DEFECTIVE IN ANY WAY OUT OF OR IN CONNECTION WITH THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE PACKAGE, EVEN IF ADVISED OF THE USE OF THIS LICENSE OR YOUR USE OR OTHER EXPLOITATION OF THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO LICENSEE OR ANY DERIVATIVE THEREOF, EVEN IF SUCH PARTY SHALL HAVE BEEN INFORMED OF THE SOFTWARE FOR ANY CLAIM, DAMAGES OR LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING PYTHON, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR ANY OTHER CONTRIBUTOR, OR ANY DISTRIBUTOR OF COVERED CODE, OR ANY AND ALL OTHER COMMERCIAL DAMAGES OR LOSSES, EVEN IF ADVISED OF THE LICENSED PRODUCT IS AUTHORIZED HEREUNDER EXCEPT UNDER THIS DISCLAIMER. TERMINATION. 8.1. This License Agreement does not incorporate text that you conspicuously and appropriately publish on each copy of this License and any related settlement negotiations. The Indemnified Contributor must: a) promptly notify the Commercial Distributor in connection with the installation, use or inability to use Covered Code, and keep intact all the source code, object code form under the terms and conditions for copying, distributing or modifying the License.',
    'Apple may publish new versions of the date You accept this license. You may reproduce the above copyright notice, this list of all Your Externally Deployed Modifications must be included with each copy of this License Agreement shall be governed by California law provisions (except to the Licensed Product. Nothing in this license or (at your option) any later version published by the GNU Free Documentation License.',
    'In such an action for patent infringement against You in that license before distributing the Program which: (i) are separate modules of software distributed under a particular purpose; ii) effectively excludes on behalf of all Contributors all liability for damages, including direct, indirect, special, incidental and consequential damages, such as FTP or HTTP or by copyrighted interfaces, the original licensor to copy, distribute, or modify the terms of this License. Limitation of Liability. UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE POSSIBILITY THEREOF.',
    'This License Agreement shall terminate as of the NOTICE text from the Public Domain or from the Copyright Holder maintains some artistic control over the development of that Contributor with its exercise of rights under this License. In particular, the act of transferring a copy, and you are not the Current Maintainer is not already Covered Code under the terms of this Agreement , including but not limited to patent issues), conditions are met: 1. Redistributions of source code form: it must be made available to others under (i) the Original Code, and if a Distributor Fee, and with or without modifications, and in any such warranty, support, indemnity or liability obligation is offered by You to distribute such modifications under the GFDL, review the page in a lawsuit), then any patent licenses granted in Sections 2(a) and 2(b) above, Recipient receives no rights or otherwise.',
    'As a condition to exercising the rights granted by that Contributor alone and not on behalf of all derivatives of that version or related documentation and collateral materials stating that the Program itself (excluding combinations of the Covered Code under Your Applicable Patent Rights and other proprietary notices and associated documentation files (the "Software"), to deal with the Base Interpreter, the replacement component of the following: a) cause the whole of the GNU General Public License. The "Program", below, refers to the Licensed Product, or (ii) ownership of such a way that you have co-authored with others, you can do these things. To protect your rights, we need to ensure or guarantee that the following in a commercial product offering.',
    'The obligations in this license requires that the Modifications you distribute them as separate works. But when you distribute the Source Code of Covered Code. However, You may charge fees for other licensees extend to the personal jurisdiction of, and venue in, the defense and any other intellectual property claims, each Contributor must identify itself as the originator of its Contribution alone or in part pre-release, untested, or not fully tested works. The Covered Code is a Current Maintainer upon request provided they then update their communication data within one month.',
    'If the Current Maintainer of the Work, transformations of the Work and reproducing the content of the Licensed Product against such Respondent. If within said Notice Period. Reasonable Value of This License or the Derived Program from a Contributor if it has sufficient copyright rights in the file for the Package. If you institute patent litigation against any party wishing to do so, attach the following unique, persistent identifier (known as a component of the Work; if your distribution of the Work.',
  ]

  for (let i = 0; i <= 100; i++ ) {
    legalIpsum.push(legalIpsumText.map((txt, idx) => <p key={idx}>{txt}</p>))
  }
  
  return (
    <div>
      <Button onClick={handleClickOpen} className={classes.button}>
        Privacy Policy
      </Button>
      <Dialog fullScreen open={open} onClose={handleClose} TransitionComponent={Transition}>
        <AppBar className={classes.appBar}>
          <Toolbar>
            {/* <IconButton edge="start" color="inherit" onClick={handleClose} aria-label="close">
              <CloseIcon />
            </IconButton> */}
            <Typography variant="h6" className={classes.title}>
              Privacy Policy
            </Typography>
            <Button color="inherit" onClick={handleClose}>
              Accept
            </Button>
          </Toolbar>
        </AppBar>
        <Container>
            {legalIpsum}

          {/* <img src='https://www.exterro.com/images/uploads/comicsmemes/_360xAUTO_stretch_center-center_none/Zuckerberg-Meme.jpg' /> */}
        </Container>
      </Dialog>
    </div>
  );
}

export default PrivacyPolicy